### ISSUE TITLE
After saving info in Description, the button still says "Submit".

### ISSUE THREAD

**Issue by Jibsman** [EDCD/Orbis#10]
Create a build & edit it. Change items in the Description; Title, image, and/or Build description, and click the Submit button. After the text is saved, the button still says "Submit". Perhaps until edits are made, the button should say "Close"? Only when text is changed the button changes to "Submit"? Not sure if this is possible, but it appears the way to get back to your list of ships is clicking "My Profile", which is not intuitive.

**Comment by jessb321** [comment]
Yeah, seems like a good suggestion to me. Will fix soontm
