### ISSUE TITLE
Going to another page using the numbers or <  > symbols changes pages but does not return you to the top of the page.

### ISSUE THREAD

**Issue by Jibsman** [EDCD/Orbis#12]
Going to another page using the numbers or <  > symbols changes pages but does not return you to the top of the page.
Google Chrome:
Start on Page 1, scroll down to see all the ships. Click the number 2 or the > symbol and it goes to the next page, but the page displayed is at the bottom of the list of ships. 
I would think this would return you to the top of the page, so you can continue scrolling down, then go to the next page.
Bug or Feature Request? I can move this if it's not a bug.

**Comment by jessb321** [comment]
Yeah, this is more of a bug but I will fix this soontm
