### ISSUE TITLE
Need to log in after deleting 2 ships.

### ISSUE THREAD

**Issue by Jibsman** [EDCD/Orbis#5]
Log In
Select My Profile
Select a ship by clicking View
Click Edit Build Details
Click Delete
User is returned to main page, not My Profile <- Different issue
Click My Profile again to see my ships.
Click My Profile again to see my ships <- different bug
Select a ship with View
Click Edit Build Details
Click Delete
User is returned to main page, not My Profile <- Different issue
I am now logged out. "My Profile" is no longer there.
Click the Login Dude
I am automatically logged in again. Did not go through the login ID/PW exercise.

Also if I happen to tab between sites I can get logged out when tabbing back to Orbis.

**Comment by jessb321** [comment]
I'm pretty sure this was an issue with the session store. Deploying a hopeful fix with a different store - 5749f8e69c3ecdee35932a1f939caa7a341fd4f3

**Comment by jessb321** [comment]
Should be fixed. Feel free to ping if not.
