### ISSUE TITLE
Reducing the window size cuts off text for individual ships

### ISSUE THREAD

**Issue by Jibsman** [EDCD/Orbis#6]
Using Google Chrome on W.10.RS4 System.
Reducing the size of the window and ship text starts getting cut off.
Possibly set minimum size for the Tab or at least the ships, rearranging columns until it's only one column, but can still see the entire details for each ship, if that is possible.

**Comment by jessb321** [comment]
Fixed in f6d4adef5adc4116fff4b7699e358fceca532fa1
