### ISSUE TITLE
Voting goes from 1 to -1, skipping 0. Bug or intentional?

### ISSUE THREAD

**Issue by Jibsman** [EDCD/Orbis#8]
Not sure if this is intentional or not. The Vote starts at 0. If I click Upvote it goes to 1. If I click Downvote it goes to -1. Shouldn't it go back to 0 before -1? I think that's how Reddit does this.
Either way kinda makes sense...

**Comment by jessb321** [comment]
This is sort of intended. What is happening is the default score is 0
You upvote it to 1
You then change your vote to a -1 aka a downvote
The score changes to reflect the current score aka 0 -1

**Comment by jessb321** [comment]
Also, Reddit does funky things with negative votes whereas Orbis is for the moment straight scoring

**Comment by jessb321** [comment]
Will close this since it was more of a question.
